#!/usr/bin/env sh

DOTFILES="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

# Zsh
# ln -sf $DOTFILES/zsh/zshrc $HOME/.zshrc


if [ ! -f "$PRIVATE_FILE" ]; then
    ln -sf $DOTFILES/zsh/private $HOME/.private
    echo "Private file initiated at ~/.private . Make sure to source your private file into your $shell_rc"
fi

# Neovim
# rm -rf $HOME/.config/nvim
# ln -s $DOTFILES/nvim $HOME/.config/nvim

# Kitty
# rm -rf $HOME/.config/kitty
# ln -s $DOTFILES/kitty $HOME/.config/kitty

# Tmux
ln -sf $DOTFILES/tmux/tmux.conf $HOME/.tmux.conf

# Git
# ln -sf $DOTFILES/git/gitconfig $HOME/.gitconfig
echo "Skipping git to avoid overwriting existing configuration"
ln -sf $DOTFILES/git/gitignore_global $HOME/.gitignore_global

# Phpactor
rm -rf $HOME/.config/phpactor
ln -s $DOTFILES/phpactor $HOME/.config/phpactor

# Scripts
mkdir -p $HOME/.local/bin

# ln -sf $DOTFILES/scripts/t $HOME/.local/bin/t
# ln -sf $DOTFILES/scripts/deliver $HOME/.local/bin/deliver

# Oh My Zsh
# if [ ! -d "$HOME/.oh-my-zsh" ]; then
#     KEEP_ZSHRC=yes sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
# f>> 


echo ""
